export const enemies = [
  { id: 1, name: "Big Johninator", icon: ["/external/wiki/images/BigJohnator.webp"], wikiLink: "/external/wiki/Big_Johninator" },
  { id: 2, name: "Cancerous Rodent", icon: ["/external/wiki/images/Cancerous_Rodent.webp"], wikiLink: "/external/wiki/Cancerous_Rodent#Cancerous_Rodent-0" },
  { id: 3, name: "Very Cancerous Rodent", icon: ["/external/wiki/images/Very_Cancerous_Rodent.webp"], wikiLink: "/external/wiki/Cancerous_Rodent#Very_Cancerous_Rodent-0" },
  { id: 4, name: "Cerberus", icon: ["/external/wiki/images/Cerberus.webp"], wikiLink: "/external/wiki/Cerberus" },
  { id: 5, name: "Deathcatcher", icon: ["/external/wiki/images/Deathcatcher.webp"], wikiLink: "/external/wiki/Deathcatcher" },
  { id: 6, name: "Drone", icon: ["/external/wiki/images/Drone.webp"], wikiLink: "/external/wiki/Drone" },
  { id: 7, name: "Earthmover (Central Brain)", icon: ["/external/wiki/images/Earthmover_Brain.png"], wikiLink: "/external/wiki/Earthmover#Central_Brain-0" },
  { id: 8, name: "1000-THR Defence System (Mainframe)", icon: ["/external/wiki/images/Earthmover_Defence_Mainframe.png"], wikiLink: "/external/wiki/Earthmover#Mainframe-0" },
  { id: 9, name: "1000-THR Defence System (Rocket Launchers)", icon: ["/external/wiki/images/CentaurRocketLauncher.webp"], wikiLink: "/external/wiki/Earthmover#Rocket_Launchers-0" },
  { id: 10, name: "1000-THR Defence System (Mortar Launchers)", icon: ["/external/wiki/images/CentaurMortar.webp"], wikiLink: "/external/wiki/Earthmover#Mortar_Launchers-0" },
  { id: 11, name: "1000-THR Defence System (Towers)", icon: ["/external/wiki/images/CentaurTower.webp"], wikiLink: "/external/wiki/Earthmover#Towers-0" },
  { id: 12, name: "Ferryman", icon: ["/external/wiki/images/Ferryman.webp"], wikiLink: "/external/wiki/Ferryman" },
  { id: 13, name: "Filth", icon: ["/external/wiki/images/Filth.webp"], wikiLink: "/external/wiki/Filth" },
  { id: 14, name: "Flesh Panopticon", icon: ["/external/wiki/images/Flesh_Panopticon.webp"], wikiLink: "/external/wiki/Flesh_Panopticon" },
  { id: 15, name: "Spotlight Eye Spawn", icon: ["/external/wiki/images/PanopticonEye.webp"], wikiLink: "/external/wiki/Flesh_Panopticon#Attacks" },
  { id: 17, name: "Flesh Prison", icon: ["/external/wiki/images/Flesh_Prison.webp"], wikiLink: "/external/wiki/Flesh_Prison" },
  { id: 18, name: "Eye Spawn", icon: ["/external/wiki/images/FleshPrisonEye.webp"], wikiLink: "/external/wiki/Flesh_Prison#Attacks" },
  { id: 20, name: "Gabriel (Judge of Hell)", icon: ["/external/wiki/images/Gabriel%2C_Judge_of_Hell.webp"], wikiLink: "/external/wiki/Gabriel" },
  { id: 21, name: "Gabriel (Apostate of Hate)", icon: ["/external/wiki/images/Gabriel%2C_Apostate_of_Hate.webp"], wikiLink: "/external/wiki/Gabriel#Apostate_of_Hate-0" },
  { id: 22, name: "Geryon", icon: ["/external/wiki/images/Geryon.webp"], wikiLink: "/external/wiki/Geryon" },
  { id: 23, name: "Gutterman", icon: ["/external/wiki/images/Gutterman.webp"], wikiLink: "/external/wiki/Gutterman" },
  { id: 24, name: "Guttertank", icon: ["/external/wiki/images/Guttertank.webp"], wikiLink: "/external/wiki/Guttertank" },
  { id: 25, name: "Hideous Mass", icon: ["/external/wiki/images/Hideous_Mass.webp"], wikiLink: "/external/wiki/Hideous_Mass" },
  { id: 26, name: "Idol", icon: ["/external/wiki/images/Idol.webp"], wikiLink: "/external/wiki/Idol" },
  { id: 27, name: "Insurrectionist", icon: ["/external/wiki/images/Insurrectionist.webp"], wikiLink: "/external/wiki/Insurrectionist" },
  { id: 28, name: "Leviathan", icon: ["/external/wiki/images/Leviathan.webp"], wikiLink: "/external/wiki/Leviathan" },
  { id: 29, name: "Malicious Face", icon: ["/external/wiki/images/Malicious_Face.webp"], wikiLink: "/external/wiki/Malicious_Face" },
  { id: 30, name: "Mannequin", icon: ["/external/wiki/images/Mannequin.webp"], wikiLink: "/external/wiki/Mannequin" },
  { id: 31, name: "Mindflayer", icon: ["/external/wiki/images/Mindflayer.webp"], wikiLink: "/external/wiki/Mindflayer" },
  { id: 32, name: "Minos Prime", icon: ["/external/wiki/images/Minos_Prime.webp"], wikiLink: "/external/wiki/Minos_Prime" },
  { id: 33, name: "Minotaur", icon: ["/external/wiki/images/Minotaur.webp"], wikiLink: "/external/wiki/Minotaur" },
  { id: 34, name: "Mirror Reaper", icon: ["/external/wiki/images/Mirror_Reaper.webp"], wikiLink: "/external/wiki/Mirror_Reaper" },
  { id: 35, name: "Mysterious Druid Knight (& Owl)", icon: ["/external/wiki/images/Mysterious_Druid_Knight_%28%26_Owl%29.webp"], wikiLink: "/external/wiki/Mysterious_Druid_Knight_(%26_Owl)" },
  { id: 36, name: "Power", icon: ["/external/wiki/images/Power.webp"], wikiLink: "/external/wiki/Power" },
  { id: 37, name: "Providence", icon: ["/external/wiki/images/Providence.webp"], wikiLink: "/external/wiki/Providence" },
  { id: 38, name: "Puppet", icon: ["/external/wiki/images/Puppet.webp"], wikiLink: "/external/wiki/Puppet" },
  { id: 39, name: "Schism", icon: ["/external/wiki/images/Schism.webp"], wikiLink: "/external/wiki/Schism" },
  { id: 40, name: "Sentry", icon: ["/external/wiki/images/Sentry.webp"], wikiLink: "/external/wiki/Sentry" },
  { id: 41, name: "Sisyphus Prime", icon: ["/external/wiki/images/Sisyphus_Prime.webp"], wikiLink: "/external/wiki/Sisyphus_Prime" },
  { id: 42, name: "Soldier", icon: ["/external/wiki/images/Soldier.webp"], wikiLink: "/external/wiki/Soldier" },
  { id: 43, name: "Something Wicked", icon: ["/external/wiki/images/Something_Wicked.webp"], wikiLink: "/external/wiki/Something_Wicked" },
  { id: 44, name: "Stalker", icon: ["/external/wiki/images/Stalker.webp"], wikiLink: "/external/wiki/Stalker" },
  { id: 45, name: "Stray", icon: ["/external/wiki/images/Stray.webp"], wikiLink: "/external/wiki/Stray" },
  { id: 46, name: "Streetcleaner", icon: ["/external/wiki/images/Streetcleaner.webp"], wikiLink: "/external/wiki/Streetcleaner" },
  { id: 47, name: "Swordsmachine", icon: ["/external/wiki/images/Swordsmachine.webp"], wikiLink: "/external/wiki/Swordsmachine" },
  { id: 50, name: "The Corpse of King Minos' Arm", icon: ["/external/wiki/images/MinosArmFull.png"], wikiLink: "/external/wiki/The_Corpse_of_King_Minos#First_Encounter-0" },
  { id: 51, name: "The Corpse of King Minos", icon: ["/external/wiki/images/The_Corpse_of_King_Minos.webp"], wikiLink: "/external/wiki/The_Corpse_of_King_Minos#Second_Encounter-0" },
  { id: 52, name: "V2", icon: ["/external/wiki/images/V2.webp"], wikiLink: "/external/wiki/V2" },
  { id: 53, name: "V2 (2nd)", icon: ["/external/wiki/images/V2_%282nd%29.webp"], wikiLink: "/external/wiki/V2#V2_(2nd)-0" },
  { id: 54, name: "Virtue", icon: ["/external/wiki/images/Virtue.webp"], wikiLink: "/external/wiki/Virtue" },
  { id: 59, name: "Ghost Drone", icon: ["/external/wiki/images/thumb/DroneGhostFull.webp/200px-DroneGhostFull.webp"], wikiLink: "/external/wiki/Drone" },
  {
    id: 66,
    name: 'Swordsmachine "Tundra/Agony"',
    icon: ["/external/wiki/images/Swordsmachine_%22Tundra%22.webp", "/external/wiki/images/Swordsmachine_%22Agony%22.webp"],
    wikiLink: "/external/wiki/Swordsmachine",
  },
  {
    id: 67,
    name: 'Insurrectionist "Angry/Rude"',
    icon: ["/external/wiki/images/Angry.png", "/external/wiki/images/Rude.png"],
    wikiLink: "/external/wiki/Insurrectionist",
  },
  {
    id: 68,
    name: 'Ferryman "Rudraksha/Agonis"',
    icon: ["/external/wiki/images/Rudraksha.png", "/external/wiki/images/Agonis.png"],
    wikiLink: "/external/wiki/Ferryman",
  },
  {
    id: 69,
    name: "Malicious Spawn",
    icon: ["/external/wiki/images/Malicious_Face.webp"],
    wikiLink: "/external/wiki/Flesh_Prison",
  },
];
