export const levels = [
  {
    id: 1,
    levelNumber: "0-1",
    name: "Into the Fire",
    orderIndex: 1,
    thumbnail: "/external/wiki/images/0-1_Into_the_Fire.webp",
    wikiLink: "/external/wiki/wiki/0-1:_Into_the_Fire",
  },
  {
    id: 2,
    levelNumber: "0-2",
    name: "The Meatgrinder",
    orderIndex: 2,
    thumbnail: "/external/wiki/images/0-2_The_Meatgrinder.webp",
    wikiLink: "/external/wiki/wiki/0-2:_The_Meatgrinder",
  },
  {
    id: 3,
    levelNumber: "0-3",
    name: "Double Down",
    orderIndex: 3,
    thumbnail: "/external/wiki/images/0-3_Double_Down.webp",
    wikiLink: "/external/wiki/wiki/0-3:_Double_Down",
  },
  {
    id: 4,
    levelNumber: "0-4",
    name: "A One-Machine Army",
    orderIndex: 4,
    thumbnail: "/external/wiki/images/0-4_A_One-Machine_Army.webp",
    wikiLink: "/external/wiki/wiki/0-4:_A_One-Machine_Army",
  },
  {
    id: 5,
    levelNumber: "0-5",
    name: "Cerberus",
    orderIndex: 5,
    thumbnail: "/external/wiki/images/0-5_Cerberus.webp",
    wikiLink: "/external/wiki/wiki/0-5:_Cerberus",
  },
  {
    id: 7,
    levelNumber: "0-S",
    name: "Something Wicked",
    orderIndex: 6,
    thumbnail: "/external/wiki/images/0-S_Something_Wicked.png",
    wikiLink: "/external/wiki/wiki/0-S:_Something_Wicked",
  },
  {
    id: 6,
    levelNumber: "0-E",
    name: "This Heat, An Evil Heat",
    orderIndex: 7,
    thumbnail: "/external/wiki/images/0-E_This_Heat%2C_An_Evil_Heat.webp",
    wikiLink: "/external/wiki/wiki/0-E:_This_Heat,_An_Evil_Heat",
  },
  {
    id: 8,
    levelNumber: "1-1",
    name: "Heart of the Sunrise",
    orderIndex: 8,
    thumbnail: "/external/wiki/images/1-1_Heart_of_the_Sunrise.webp",
    wikiLink: "/external/wiki/wiki/1-1:_Heart_of_the_Sunrise",
  },
  {
    id: 9,
    levelNumber: "1-2",
    name: "The Burning World",
    orderIndex: 9,
    thumbnail: "/external/wiki/images/1-2_The_Burning_World.webp",
    wikiLink: "/external/wiki/wiki/1-2:_The_Burning_World",
  },
  {
    id: 10,
    levelNumber: "1-3",
    name: "Halls of Sacred Remains",
    orderIndex: 10,
    thumbnail: "/external/wiki/images/1-3_Halls_of_Sacred_Remains.webp",
    wikiLink: "/external/wiki/wiki/1-3:_Halls_of_Sacred_Remains",
  },
  {
    id: 11,
    levelNumber: "1-4",
    name: "Clair de Lune",
    orderIndex: 11,
    thumbnail: "/external/wiki/images/1-4_Clair_de_Lune.webp",
    wikiLink: "/external/wiki/wiki/1-4:_Clair_de_Lune",
  },
  {
    id: 13,
    levelNumber: "1-S",
    name: "The Witless",
    orderIndex: 12,
    thumbnail: "/external/wiki/images/1-S_The_Witless.png",
    wikiLink: "/external/wiki/wiki/1-S:_The_Witless",
  },
  {
    id: 12,
    levelNumber: "1-E",
    name: "...Then Fell the Ashes",
    orderIndex: 13,
    thumbnail: "/external/wiki/images/1-E_...Then_Fell_the_Ashes.webp",
    wikiLink: "/external/wiki/wiki/1-E:_...Then_Fell_the_Ashes",
  },
  {
    id: 14,
    levelNumber: "2-1",
    name: "Bridgeburner",
    orderIndex: 14,
    thumbnail: "/external/wiki/images/2-1_In_the_Air_Tonight.webp",
    wikiLink: "/external/wiki/wiki/2-1:_Bridgeburner",
  },
  {
    id: 15,
    levelNumber: "2-2",
    name: "Death at 20,000 Volts",
    orderIndex: 15,
    thumbnail: "/external/wiki/images/2-2_Death_at_20%2C000_Volts.webp",
    wikiLink: "/external/wiki/wiki/2-2:_Death_at_20,000_Volts",
  },
  {
    id: 16,
    levelNumber: "2-3",
    name: "Sheer Heart Attack",
    orderIndex: 16,
    thumbnail: "/external/wiki/images/2-3_Sheer_Heart_Attack.webp",
    wikiLink: "/external/wiki/wiki/2-3:_Sheer_Heart_Attack",
  },
  {
    id: 17,
    levelNumber: "2-4",
    name: "Court of the Corpse King",
    orderIndex: 17,
    thumbnail: "/external/wiki/images/2-4_Court_of_the_Corpse_King.webp",
    wikiLink: "/external/wiki/wiki/2-4:_Court_of_the_Corpse_King",
  },
  {
    id: 18,
    levelNumber: "2-S",
    name: "All-Imperfect Love Song",
    orderIndex: 18,
    thumbnail: "/external/wiki/images/2-S_All-Imperfect_Love_Song.png",
    wikiLink: "/external/wiki/wiki/2-S:_All-Imperfect_Love_Song",
  },
  {
    id: 19,
    levelNumber: "3-1",
    name: "Belly of the Beast",
    orderIndex: 19,
    thumbnail: "/external/wiki/images/3-1_Belly_of_the_Beast.webp",
    wikiLink: "/external/wiki/wiki/3-1:_Belly_of_the_Beast",
  },
  {
    id: 20,
    levelNumber: "3-2",
    name: "In the Flesh",
    orderIndex: 20,
    thumbnail: "/external/wiki/images/3-2_In_the_Flesh.webp",
    wikiLink: "/external/wiki/wiki/3-2:_In_the_Flesh",
  },
  {
    id: 42,
    levelNumber: "P-1",
    name: "Soul Survivor",
    orderIndex: 21,
    thumbnail: "/external/wiki/images/P-1_Soul_Survivor.webp",
    wikiLink: "/external/wiki/wiki/P-1:_Soul_Survivor",
  },
  {
    id: 21,
    levelNumber: "4-1",
    name: "Slaves to Power",
    orderIndex: 22,
    thumbnail: "/external/wiki/images/4-1_Slaves_to_Power.webp",
    wikiLink: "/external/wiki/wiki/4-1:_Slaves_to_Power",
  },
  {
    id: 22,
    levelNumber: "4-2",
    name: "God Damn the Sun",
    orderIndex: 23,
    thumbnail: "/external/wiki/images/4-2_God_Damn_the_Sun.webp",
    wikiLink: "/external/wiki/wiki/4-2:_God_Damn_the_Sun",
  },
  {
    id: 23,
    levelNumber: "4-3",
    name: "A Shot in the Dark",
    orderIndex: 24,
    thumbnail: "/external/wiki/images/4-3_A_Shot_in_the_Dark.webp",
    wikiLink: "/external/wiki/wiki/4-3:_A_Shot_in_the_Dark",
  },
  {
    id: 24,
    levelNumber: "4-4",
    name: "Clair de Soleil",
    orderIndex: 25,
    thumbnail: "/external/wiki/images/4-4_Clair_de_Soleil.webp",
    wikiLink: "/external/wiki/wiki/4-4:_Clair_de_Soleil",
  },
  {
    id: 25,
    levelNumber: "4-S",
    name: "Clash of the Brandicoot",
    orderIndex: 26,
    thumbnail: "/external/wiki/images/4-S_Clash_of_the_Brandicoot.png",
    wikiLink: "/external/wiki/wiki/4-S:_Clash_of_the_Brandicoot",
  },
  {
    id: 26,
    levelNumber: "5-1",
    name: "In the Wake of Poseidon",
    orderIndex: 27,
    thumbnail: "/external/wiki/images/5-1_In_the_Wake_of_Poseidon.webp",
    wikiLink: "/external/wiki/wiki/5-1:_In_the_Wake_of_Poseidon",
  },
  {
    id: 27,
    levelNumber: "5-2",
    name: "Waves of the Starless Sea",
    orderIndex: 28,
    thumbnail: "/external/wiki/images/5-2_Waves_of_the_Starless_Sea.webp",
    wikiLink: "/external/wiki/wiki/5-2:_Waves_of_the_Starless_Sea",
  },
  {
    id: 28,
    levelNumber: "5-3",
    name: "Ship of Fools",
    orderIndex: 29,
    thumbnail: "/external/wiki/images/5-3_Ship_of_Fools.webp",
    wikiLink: "/external/wiki/wiki/5-3:_Ship_of_Fools",
  },
  {
    id: 29,
    levelNumber: "5-4",
    name: "Leviathan",
    orderIndex: 30,
    thumbnail: "/external/wiki/images/5-4_Leviathan.webp",
    wikiLink: "/external/wiki/wiki/5-4:_Leviathan",
  },
  {
    id: 30,
    levelNumber: "5-S",
    name: "I Only Say Morning",
    orderIndex: 31,
    thumbnail: "/external/wiki/images/5-S_I_Only_Say_Morning.png",
    wikiLink: "/external/wiki/wiki/5-S:_I_Only_Say_Morning",
  },
  {
    id: 31,
    levelNumber: "6-1",
    name: "Cry for the Weeper",
    orderIndex: 32,
    thumbnail: "/external/wiki/images/6-1_Cry_for_the_Weeper.webp",
    wikiLink: "/external/wiki/wiki/6-1:_Cry_for_the_Weeper",
  },
  {
    id: 32,
    levelNumber: "6-2",
    name: "Aesthetics of Hate",
    orderIndex: 33,
    thumbnail: "/external/wiki/images/6-2_Aesthetics_of_Hate.webp",
    wikiLink: "/external/wiki/wiki/6-2:_Aesthetics_of_Hate",
  },
  {
    id: 43,
    levelNumber: "P-2",
    name: "Wait of the World",
    orderIndex: 34,
    thumbnail: "/external/wiki/images/P-2_Wait_of_the_World.webp",
    wikiLink: "/external/wiki/wiki/P-2:_Wait_of_the_World",
  },
  {
    id: 33,
    levelNumber: "7-1",
    name: "Garden of Forking Paths",
    orderIndex: 35,
    thumbnail: "/external/wiki/images/7-1_Garden_of_Forking_Paths.webp",
    wikiLink: "/external/wiki/wiki/7-1:_Garden_of_Forking_Paths",
  },
  {
    id: 34,
    levelNumber: "7-2",
    name: "Light Up the Night",
    orderIndex: 36,
    thumbnail: "/external/wiki/images/7-2_Light_Up_the_Night.webp",
    wikiLink: "/external/wiki/wiki/7-2:_Light_Up_the_Night",
  },
  {
    id: 35,
    levelNumber: "7-3",
    name: "No Sound, No Memory",
    orderIndex: 37,
    thumbnail: "/external/wiki/images/7-3_No_Sound_No_Memory.webp",
    wikiLink: "/external/wiki/wiki/7-3:_No_Sound,_No_Memory",
  },
  {
    id: 36,
    levelNumber: "7-4",
    name: "...Like Antennas to Heaven",
    orderIndex: 38,
    thumbnail: "/external/wiki/images/7-4_Like_Antennas_to_Heaven.webp",
    wikiLink: "/external/wiki/wiki/7-4:_...Like_Antennas_to_Heaven",
  },
  {
    id: 37,
    levelNumber: "7-S",
    name: "Hell Bath No Fury",
    orderIndex: 39,
    thumbnail: "/external/wiki/images/7-S_Hell_Bath_No_Fury.png",
    wikiLink: "/external/wiki/wiki/7-S:_Hell_Bath_No_Fury",
  },
  {
    id: 38,
    levelNumber: "8-1",
    name: "Hurtbreak Wonderland",
    orderIndex: 40,
    thumbnail: "/external/wiki/images/8-1_Hurtbreak_Wonderland.png",
    wikiLink: "/external/wiki/wiki/8-1:_Hurtbreak_Wonderland",
  },
  {
    id: 39,
    levelNumber: "8-2",
    name: "Through the Mirror",
    orderIndex: 41,
    thumbnail: "/external/wiki/images/8-2_Through_the_Mirror.png",
    wikiLink: "/external/wiki/wiki/8-2:_Through_the_Mirror",
  },
  {
    id: 40,
    levelNumber: "8-3",
    name: "Disintegration Loop",
    orderIndex: 42,
    thumbnail: "/external/wiki/images/8-3_Disintegration_Loop.png",
    wikiLink: "/external/wiki/wiki/8-3:_Disintegration_Loop",
  },
  {
    id: 41,
    levelNumber: "8-4",
    name: "Final Flight",
    orderIndex: 43,
    thumbnail: "/external/wiki/images/8-4_Final_Flight.png",
    wikiLink: "/external/wiki/wiki/8-4:_Final_Flight",
  },
];
